# Site Settings
baseurl: ""
url : "https://Heeseok-Jeong.github.io"

# Blog Settings
theme_settings :
  title : Grape Theme
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Heeseok Jeong
    description : creator of Grape-Theme! Grape-Theme is my first jekyll theme and you can customize this theme easily.
    experience :
      - start : 2020-07-01
        end : 2020-08-25
        experience : KONAN Technology, Intern
    skills : 
      - skill : Java
        value : 80  # Percent value
        
  # Icons
  icons :
    email:  "dldydldy@naver.com"
    linkedin:  # Full URL 
    github: Heeseok-Jeong
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
