# Site Settings
baseurl: ""
url : "https://Heeseok-Jeong.github.io"

# Blog Settings
theme_settings :
  title : Heeseok Jeong
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Heeseok Jeong
    description : Developer.
    experience :
      - start : 2020-07-01
        end : 2020-08-25
        experience : KONAN Technology, Intern
      - start : 2021-01-05
        # end : 2020-08-25
        experience : SSAFY, 5th
    skills :
      - skill : Java
        value : 80
      - skill : Python
        value : 85

  # Icons
  icons :
    email:  "dldydldy@naver.com"
    linkedin:  # Full URL
    github: Heeseok-Jeong
    gitlab:
    bitbucket:
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname : heeseok-jeong

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
